# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndata.proto\"#\n\x0b\x64\x61taRequest\x12\x14\n\x0crequest_data\x18\x01 \x01(\t\"%\n\x0c\x64\x61taResponse\x12\x15\n\rresponse_data\x18\x01 \x01(\t27\n\x0c\x64\x61ta_Service\x12\'\n\x06GetMsg\x12\x0c.dataRequest\x1a\r.dataResponse\"\x00\x62\x06proto3'
)




_DATAREQUEST = _descriptor.Descriptor(
  name='dataRequest',
  full_name='dataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_data', full_name='dataRequest.request_data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=49,
)


_DATARESPONSE = _descriptor.Descriptor(
  name='dataResponse',
  full_name='dataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_data', full_name='dataResponse.response_data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['dataRequest'] = _DATAREQUEST
DESCRIPTOR.message_types_by_name['dataResponse'] = _DATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

dataRequest = _reflection.GeneratedProtocolMessageType('dataRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATAREQUEST,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:dataRequest)
  })
_sym_db.RegisterMessage(dataRequest)

dataResponse = _reflection.GeneratedProtocolMessageType('dataResponse', (_message.Message,), {
  'DESCRIPTOR' : _DATARESPONSE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:dataResponse)
  })
_sym_db.RegisterMessage(dataResponse)



_DATA_SERVICE = _descriptor.ServiceDescriptor(
  name='data_Service',
  full_name='data_Service',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=90,
  serialized_end=145,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMsg',
    full_name='data_Service.GetMsg',
    index=0,
    containing_service=None,
    input_type=_DATAREQUEST,
    output_type=_DATARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATA_SERVICE)

DESCRIPTOR.services_by_name['data_Service'] = _DATA_SERVICE

# @@protoc_insertion_point(module_scope)
