version: "3"

services:
  db:
    extends:
      file: ./common-services.yml
      service: db

  build:
    extends:
      file: ./docker-compose.yml
      service: roscore
    container_name: build
    command: "/home/augbooth/docker/scripts/build.bash"
    environment:
      - CONTAINER_NAME=build
    depends_on:
      - db  # for building backoffice objects
