FROM python:3.9

#
WORKDIR /code/app

#
COPY ./requirements.txt requirements.txt

#
RUN pip install --no-cache-dir --upgrade -r requirements.txt && rm requirements.txt


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
