version: "3"
services:
  db:
    extends:
      file: ./common-services.yml
      service: db

  redis:
    extends:
      file: ./common-services.yml
      service: redis

  nginx:
    extends:
      file: ./common-services.yml
      service: nginx
    volumes:
      # for v3.1 and later
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
      - {{ fleet_repo_path }}/fleet_gui/:/var/www/backoffice:rw

  fleet_manager:
    extends:
      file: ./common-services.yml
      service: lionel
    restart: always
    container_name: fleet_manager
    command: "/home/augbooth/docker/scripts/fleet_manager.bash"
    volumes:
      - {{ catkin_workspace }}:/home/augbooth/catkin_ws:rw
      - {{ fleet_repo_path }}:/home/augbooth/catkin_ws/src/boothbot-fleet:rw
    environment:
      - CONTAINER_NAME=fleet_manager
    depends_on:
      - db
      - redis
      - nginx

  roscore:
    extends:
      file: ./common-services.yml
      service: lionel
    restart: always
    user: augbooth
    command: stdbuf -o L roscore
    network_mode: "host"
